#!/usr/bin/env bash
# setup-grafana-monitoring.sh — Interactive setup for Grafana Cloud Free Tier
# Run: ./monitoring/setup-grafana-monitoring.sh
set -euo pipefail

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   Grafana Cloud Free Tier — Portfolio Platform Monitoring   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "You need 3 pieces of info from https://grafana.com → My Account:"
echo "  1. Prometheus remote-write URL + user ID"
echo "  2. Loki push URL + user ID"  
echo "  3. API Key (MetricsPublisher role)"
echo ""

ENV_FILE="$(dirname "$0")/../.env.monitoring"

# ─── Collect credentials ───────────────────────────────────────────────────────
read -rp "Prometheus remote-write URL: " PROM_URL
read -rp "Prometheus user ID (numeric): " PROM_USER
read -rp "Loki push URL: " LOKI_URL
read -rp "Loki user ID (numeric): " LOKI_USER
read -rp "API Key (glc_...): " API_KEY

# ─── Write .env.monitoring ─────────────────────────────────────────────────────
cat > "$ENV_FILE" << EOF
# Generated by setup-grafana-monitoring.sh on $(date +%Y-%m-%d)
# Grafana Cloud credentials for org: loyalcaravan951

GRAFANA_PROMETHEUS_URL=${PROM_URL}
GRAFANA_PROMETHEUS_USER=${PROM_USER}
GRAFANA_API_KEY=${API_KEY}

GRAFANA_LOKI_URL=${LOKI_URL}
GRAFANA_LOKI_USER=${LOKI_USER}

# Service URLs — for local dev, services run on these ports:
NOTIFICATION_SERVICE_URL=host.docker.internal:8080
ADMIN_SERVICE_URL=host.docker.internal:8081
SEARCH_INDEXER_URL=host.docker.internal:8082
RAG_INDEXER_URL=host.docker.internal:8083
AGENT_SERVICE_URL=host.docker.internal:8090
MCP_GATEWAY_URL=host.docker.internal:8091
AGGREGATOR_SERVICE_URL=host.docker.internal:8093
ALERTS_SERVICE_URL=host.docker.internal:8094
EOF

echo ""
echo "✅ Written to: $ENV_FILE"
echo ""

# ─── Start Alloy ──────────────────────────────────────────────────────────────
echo "Starting Grafana Alloy scraper..."
cd "$(dirname "$0")/.."
docker compose -f docker-compose.monitoring.yml --env-file .env.monitoring up -d

echo ""
echo "✅ Alloy is running! Check status:"
echo "   docker compose -f docker-compose.monitoring.yml logs -f"
echo "   Alloy UI: http://localhost:12345"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Next: Import Spring Boot dashboard in Grafana Cloud"
echo "  1. Go to your Grafana instance → Dashboards → Import"
echo "  2. Enter dashboard ID: 19004"
echo "  3. Select your Prometheus data source"
echo "  4. Click Import"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
