package site.yuqi.admin.domain;

public enum AuditAction {
    CREATE,
    UPDATE,
    PUBLISH,
    ROLLBACK,
    ARCHIVE,
    DELETE,
    REINDEX_RAG,
    REINDEX_SEARCH,
    RETRY_INDEXING_JOB,
    RETRY_OUTBOX_EVENT,
    REPLAY_OUTBOX_EVENT,
    ADMIN_USER_UPSERT,
    ADMIN_USER_STATUS_UPDATE
}
